In [2]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [3]:
# nltk
import nltk

# stopwords
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

# stemming
from nltk.stem.porter import PorterStemmer  
st = PorterStemmer()

from cleantext import clean

In [4]:
clean('HELLLO !!! this is Ashura, we are happy to welcome you all', punct=True, lowercase=True, stemming=False)

'helllo  this is ashura we are happy to welcome you all'

In [26]:
clean('Playing, Singing, Dancing', punct=True, lowercase=True)

'playing singing dancing'

In [5]:
# making a function using both clean and nltk to clean the texts

def change(text):
    text = clean(text, lowercase=True, punct=True, stemming=False, stopwords=False)
    text = nltk.word_tokenize(text)
    

    temp = []
    
    # stopwords
    for word in text:
        if word not in stop_words:
            # stemming
            word = st.stem(word)
            temp.append(word)
    

    # joining temp with a single string
    text = " ".join(temp)
    return text

In [6]:
change('hii there my name is king, living here. !!!')

'hii name king live'

### Using Lemmatization instead of stemming to keep the original root word

In [7]:
import nltk

from nltk.tokenize import word_tokenize

from nltk.corpus import stopwords
stop_words = stopwords.words('english')

from nltk.stem import WordNetLemmatizer
lmt = WordNetLemmatizer()

from cleantext import clean

In [8]:
help(WordNetLemmatizer)

Help on class WordNetLemmatizer in module nltk.stem.wordnet:

class WordNetLemmatizer(builtins.object)
 |  WordNet Lemmatizer
 |
 |  Provides 3 lemmatizer modes: _morphy(), morphy() and lemmatize().
 |
 |  lemmatize() is a permissive wrapper around _morphy().
 |  It returns the shortest lemma found in WordNet,
 |  or the input string unchanged if nothing is found.
 |
 |  >>> from nltk.stem import WordNetLemmatizer as wnl
 |  >>> print(wnl().lemmatize('us', 'n'))
 |  u
 |
 |  >>> print(wnl().lemmatize('Anythinggoeszxcv'))
 |  Anythinggoeszxcv
 |
 |  Methods defined here:
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  lemmatize(self, word: str, pos: str = 'n') -> str
 |      Lemmatize `word` by picking the shortest of the possible lemmas,
 |      using the wordnet corpus reader's built-in _morphy function.
 |      Returns the input word unchanged if it cannot be found in WordNet.
 |
 |      >>> from nltk.stem import WordNetLemmatizer as wnl
 |      >>> print(wnl().lemmatize('dogs'))
 |      dog
 |      >>> print(wnl().lemmatize('churches'))
 |      church
 |      >>> print(wnl().lemmatize('aardwolves'))
 |      aardwolf
 |      >>> print(wnl().lemmatize('abaci'))
 |      abacus
 |      >>> print(wnl().lemmatize('hardrock'))
 |      hardrock
 |
 |      :param word: The input word to lemmatize.
 |      :type word: str
 |      :param pos: The Part Of Speech tag. Valid options are `"n"` for nouns,
 |          `"v"` for verbs, `"a"` for adjectives, `"r"` for adverbs and `"s"`
 |          for satellite adjectives.
 |      :type pos: str
 |      :return: The shortest lemma of `word`, for the given `pos`.
 |
 |  morphy(self, form, pos=None, check_exceptions=True)
 |      morphy() is a restrictive wrapper around _morphy().
 |      It returns the first lemma found in WordNet,
 |      or None if no lemma is found.
 |
 |      >>> from nltk.stem import WordNetLemmatizer as wnl
 |      >>> print(wnl().morphy('us', 'n'))
 |      us
 |
 |      >>> print(wnl().morphy('catss'))
 |      None
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

In [9]:
lmt.lemmatize('I am playing cricket right now to make the winning team make proud on me.', pos='v')

'I am playing cricket right now to make the winning team make proud on me.'

In [10]:
# printing both the original and root word


sentence = 'I am playing cricket right now to make the winning team make proud on me.'
ans = [(word, lmt.lemmatize(word, pos='v')) for word in sentence.split()]

print(ans)

[('I', 'I'), ('am', 'be'), ('playing', 'play'), ('cricket', 'cricket'), ('right', 'right'), ('now', 'now'), ('to', 'to'), ('make', 'make'), ('the', 'the'), ('winning', 'win'), ('team', 'team'), ('make', 'make'), ('proud', 'proud'), ('on', 'on'), ('me.', 'me.')]

In [11]:
from nltk.stem import WordNetLemmatizer
lmt = WordNetLemmatizer()

In [12]:
# making a function that do tokenization, stopword removal, and lemmatization

def transform(text):
    text = clean(text, lowercase=True, punct=True, stopwords=False, stemming=False)
    text = word_tokenize(text)

    temp = []
    for word in text:
        if word not in stop_words:
            # lemmatization
            word = lmt.lemmatize(word, pos='v')
            temp.append(word)
    
    text = temp[:]
    return " ".join(text)

In [13]:
transform('Holla !!!, Hope you are fine.')

'holla hope fine'

### Using `autocorrect`

In [14]:
from autocorrect import Speller
spell = Speller('en')

In [15]:
print(spell('mussage'))
print(spell('laor'))
print(spell('hiiiiii this is sooooooo cooooollll'))

message
labor
hiiiiii this is sooooooo cooooollll

### Using TF-IDF

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [17]:
tfidf.fit_transform(['Hello World']).toarray()        
# REMEMBER : while using tfidf you must pass the input in a list format, coz tfidf only takes strings in list format, it doesn't take strings in raw format
# REMEMBER : which using tfidf you must need to convert it into an array, else it will just throw some numbers

array([[0.70710678, 0.70710678]])

In [18]:
tfidf.get_feature_names_out            # printing the feature names

Giving a list of input stings and checking for their vector format

In [19]:
texts = [
    "love product amazing",
    "terrible service awful",
    "love customer service",
    "product okay nothing special"
]

ans = tfidf.fit_transform(texts)

print(ans.toarray())
print()
print(tfidf.get_feature_names_out())

[[0.66767854 0.         0.         0.52640543 0.         0.
  0.52640543 0.         0.         0.        ]
 [0.         0.61761437 0.         0.         0.         0.
  0.         0.48693426 0.         0.61761437]
 [0.         0.         0.66767854 0.52640543 0.         0.
  0.         0.52640543 0.         0.        ]
 [0.         0.         0.         0.         0.52547275 0.52547275
  0.41428875 0.         0.52547275 0.        ]]

['amazing' 'awful' 'customer' 'love' 'nothing' 'okay' 'product' 'service'
 'special' 'terrible']

The above code is not good, coz it is taking the entire sentence as an input, we need to give it inputs in word by using `word_tokenize()`

In [20]:
df = pd.read_csv("datasets/sentiment-analysis.csv")
df.head(5)

  Text, Sentiment, Source, Date/Time, User ID, Location, Confidence Score
0  "I love this product!", Positive, Twitter, 202...
1  "The service was terrible.", Negative, Yelp Re...
2  "This movie is amazing!", Positive, IMDb, 2023...
3  "I'm so disappointed with their customer suppo...
4  "Just had the best meal of my life!", Positive...

In [21]:
data = df['Text, Sentiment, Source, Date/Time, User ID, Location, Confidence Score'].str.split(',', expand=True)
data.columns = ['text', 'sentiment', 'source', 'date/time', 'ID', 'location', 'confidence_score']

In [22]:
data.head(6)

,text,sentiment,source,date/time,ID,location,confidence_score
0,"""I love this product!""",Positive,Twitter,2023-06-15 09:23:14,@user123,New York,0.85
1,"""The service was terrible.""",Negative,Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,0.65
2,"""This movie is amazing!""",Positive,IMDb,2023-06-15 14:10:22,moviefan789,London,0.92
3,"""I'm so disappointed with their customer suppo...",Negative,Online Forum,2023-06-15 17:35:11,forumuser1,Toronto,0.78
4,"""Just had the best meal of my life!""",Positive,TripAdvisor,2023-06-16 08:50:59,foodie22,Paris,0.88
5,"""The quality of this product is subpar.""",Negative,Amazon Reviews,2023-06-16 10:15:27,shopper123,San Francisco,0.72